### ISSUE TITLE
Issues for mediocres

### ISSUE THREAD

**Issue by himanshub16** [giampaolo/psutil#1034]
I realise this project requires considerable knowledge and expertise.
Still, I like it and want to contribute to it. Are there any simple issues/guide where I can start from?

**Comment by himanshub16** [comment]
I would recommend to label issues as 'bitesize', or as per difficulty level.

**Comment by giampaolo** [comment]
Off the top of my head: I need to have a script that checks for broken links in the doc (this file: https://raw.githubusercontent.com/giampaolo/psutil/master/docs/index.rst). More or less it should:
* collect all urls by using a regular expression
* for each url make an HTTP request and fail it's a broken link (return code != 200 plus some other conditions I am probably missing right now).
The script should live under /scripts/internals and should be manually invoked from the Makefile every as `make check-broken-links`).
Not sure if this is something which may interest you but since I'm bad with regular expressions that would be useful to me.

Another thing which would be cool is https://github.com/giampaolo/psutil/issues/900 

Also you may want to take a look at this file:
https://github.com/giampaolo/psutil/blob/master/IDEAS
...although these are not easy tasks.

I will comment again if something else comes to mind.

**Comment by giampaolo** [comment]
Closing this out. Just ping me when you're done with exams.

**Comment by himanshub16** [comment]
:smile: I'm back for thrilling weekends.

**Comment by giampaolo** [comment]
Hey dude. Sorry but I'm flying to Amsterdam tomorrow and I'll be back on Friday so be patient. I had something for you but I forgot. I'll search for inspiration by watching Amsterdam canals and let you know when I'm back. =)
