### ISSUE TITLE
Process.username() on Windows should probably not include the domain name

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#1049]
Currently `Process().username()` on Windows returns a `"domain\\username"` string. That is bad for different reasons:
- it's inconsistent with POSIX systems which has no concept of "domain", and POSIX is what "leads the way"
- it's inconsistent with `getpass.getuser()` and `psutil.users()` which only return a username string 
- it forces you to write system dependent code; e.g. to filter processes by name:

```python
for p in psutil.process_iter(attrs=['username']):
      user = p.info['username']
      if psutil.WINDOWS:
            user = user.split('\\')[1]
      ...
```
- it's probably useless

The real strong argument for not removing is backward compatibility so I need to think about it.

**Comment by giampaolo** [comment]
From: https://serverfault.com/questions/371150/any-difference-between-domain-username-and-usernamedomain-local/371390

> The slashed format (DOMAIN\username) is actually the NetBIOS equivalent of the domain's DNS name (domain.mycompany.local).

> its really just the old NT4 and Windows 2000 compatible format but it seems to have stuck as a favorite format (its less to type!). Eventually, support for the legacy format may go from Windows.

**Comment by cowbert** [comment]
In the majority of tools that actually deal with windows environment (NET USE, wmic, etc.), user names should always be fully qualified with the domain since that is how it is associated to the actual SID (in an AD/Domain environment, the DC allocates domain logon SIDs, and therefore `MACHINE\\User` != `DOMAIN\\User`). The serverfault post is largely correct, although as you'll notice, even in the Windows Login/Lock screen, Windows 10 still lists the user as `DOMAIN\User` and not `user@Domain.AD.forest` even though krb creates sockets to `domain.ad.forest`...

**Comment by giampaolo** [comment]
I'm gonna close this out as rejected. Also Process Hacker uses the full domain/username so I'll just stick with that.
