### ISSUE TITLE
disk_io_counters() returns an empty dict

### ISSUE THREAD

**Issue by whpark70** [giampaolo/psutil#1152]
this function does not work on windows server 2012.
does not display output anything else.

**Comment by cmllr** [comment]
I don't want to spam issues with unnecessary comments, but I also can confirm this issue. In my case, psutil is installed in latest verison using pip.

**Comment by giampaolo** [comment]
Does it return an empty list on Win server 2012?

**Comment by cmllr** [comment]
I'm receiving a `{}` as result

**Comment by giampaolo** [comment]
I believe this may be due to this (`DeviceIoControl` ret code not checked):
https://github.com/giampaolo/psutil/blob/0662915f58949a4084f9fb0c278d143708cf3ede/psutil/_psutil_windows.c#L2409-L2413

This should either fix it or raise an exception instead of returning an empty dict:
https://github.com/giampaolo/psutil/commit/ab90e4e6ac73c249cf7aea7e92aec2b6a07ef041

Do you have VS compiler? Can you test this?

**Comment by giampaolo** [comment]
Actually this broke appveyor:
https://ci.appveyor.com/project/giampaolo/psutil/build/1364/job/ascpdi271b06jle3
....which also explains this:
https://github.com/giampaolo/psutil/blob/0662915f58949a4084f9fb0c278d143708cf3ede/psutil/tests/test_system.py#L673

**Comment by cmllr** [comment]
Hey @giampaolo, sorry for my late response. Do you still need feedback using the compiled mentioned commit? Do you have instructions how to compile psutil? Thanks!

**Comment by giampaolo** [comment]
You can use this wheel: https://ci.appveyor.com/api/buildjobs/x1u4yxu6bf0jwvpf/artifacts/dist/psutil-5.4.2-cp27-cp27m-win32.whl

**Comment by whpark70** [comment]
thank for your reply.
I resolved.
type on window 2012 R2 to enable performance metric collection.
c:\> diskperf -y 

have a nice day.

**Comment by cmllr** [comment]
@whpark70 thank you, this also resolved my issue!

**Comment by MohamedTaha123** [comment]
r
