### ISSUE TITLE
Process.children() is slow

### ISSUE THREAD

**Issue by pitrou** [giampaolo/psutil#1183]
```
>>> import psutil
>>> p = psutil.Process()
>>> p.children()
[]
>>> %timeit p.children()
36.1 ms ± 268 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

It seems half of that is calling `process_iter()`:
```
>>> %timeit l = list(psutil.process_iter())
20.5 ms ± 232 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

**Comment by giampaolo** [comment]
Hey Antoine! =)
`Process.children()` is inevitably slow because it has to obtain `pid` and `ppid` for all processes:
https://github.com/giampaolo/psutil/blob/3a3598e433adec73e2a9c4d5f08e658516fb1d32/psutil/__init__.py#L862-L864
We can't get away from that.

With that said, it is true that we're doing more than just that because we also call `create_time()`, even more than once ([here](https://github.com/giampaolo/psutil/blob/3a3598e433adec73e2a9c4d5f08e658516fb1d32/psutil/__init__.py#L330) and [here](https://github.com/giampaolo/psutil/blob/3a3598e433adec73e2a9c4d5f08e658516fb1d32/psutil/__init__.py#L867)

We can probably avoid that and define a utility function similar to what we have on windows:
https://github.com/giampaolo/psutil/blob/3a3598e433adec73e2a9c4d5f08e658516fb1d32/psutil/__init__.py#L851-L854
...which just returns a `{pid; ppid, ...}` map for all processes in one shot.

**Comment by pitrou** [comment]
Does that function have to be consistent? The problem is if the processes change while iterating on e.g. `/proc`.

**Comment by giampaolo** [comment]
A process which "changes" while iterating means it will disappear, in which case we'll just skip it.
They will also be skipped in case of `AccessDenied` (doc doesn't mention this - I will file a ticket for it).

**Comment by pitrou** [comment]
I see, so we can just scan quickly over `/proc`?

**Comment by giampaolo** [comment]
Yes. Same goes for all other platforms except Windows which already does this [in C](https://github.com/giampaolo/psutil/blob/3a3598e433adec73e2a9c4d5f08e658516fb1d32/psutil/_psutil_windows.c#L2980).

**Comment by giampaolo** [comment]
Addresed in #1185 and #1186. Closing.
