### ISSUE TITLE
Strip unneeded platforms from package

### ISSUE THREAD

**Issue by KOLANICH** [giampaolo/psutil#1191]
For example in the package installed on Linux I see the files for osx, windows, sunos and bsd. Though it's tolerable and the loss of space is negligible, it's not good.

**Comment by giampaolo** [comment]
The `tar.gz` (source) distribution needs to have all source files because that way psutil can be installed on any platform. What you're asking is to choose which files to copy on "install". That is just not worth the effort IMO. All installation files together are < 1MB on disk:

```
$ make build
...
$ du -h build/lib.linux-x86_64-2.7/psutil/
444K	build/lib.linux-x86_64-2.7/psutil/tests
920K	build/lib.linux-x86_64-2.7/psutil/
920K	total
```

By removing "extras" we can save what? Maybe 300K? Not sure but it won't make a huge difference considering disk space availability nowadays.  Where one should save space is for `tar.gz.` distribution, because that is downloaded from the internet, but I already took care of that some time ago (now it's around 500K).
Sorry but I'm gonna close this as rejected.
