### ISSUE TITLE
First and only battery on linux isn't always BAT0

### ISSUE THREAD

**Issue by luzader** [giampaolo/psutil#1238]
The battery on my laptop is "BAT1" and there is no "BAT0". So this check will fail:

https://github.com/giampaolo/psutil/blob/f0094db79ad9e4f2246997cb8c2046b71c465a29/psutil/_pslinux.py#L1220-L1221

It's possible this is an oddity of just my laptop (it doesn't have a second battery bay or anything exotic), but I wanted to point it out in case perhaps this is failing for others.

**Comment by giampaolo** [comment]
This should now be fixed. Thanks for the report.

**Comment by lfom** [comment]
@giampaolo Helo. I think it is not worthy opening a new issue, just to report that `psutil` could not detect the battery on my Atom-X5 convertible, but thanks to this issue I was able to make it work by searching for BA instead of just BAT (the battery is called BAPM and the adapter is ADP1).
https://github.com/giampaolo/psutil/blob/40abe5c0aa3e258161284b58cedcee1e11a66e75/psutil/_pslinux.py#L1341
