### ISSUE TITLE
Error building "Microsoft Visual C++ 14.0 is required" also with VS Tools installed

### ISSUE THREAD

**Issue by eldarioz** [giampaolo/psutil#1272]
Hi all, 

i'm trying to install apache-airflow on my Windows 10 laptop, and i had an error building psutil.
This is the error message from pip:

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

I had Visual Studio Community 2017 yet installed on my pc, so I added the VC++ support.
I tried to run pip from the Visual Studio 2017 Developer Command Prompt v15.6.1.
In this way, all the environment variables are setted by the shell itself, and i tried both x86 and x64 consoles, but i had the same results.

What is the executable called by the compile method? I'm sure that cl and msbuild executable are available from Developer Command prompt...

I attached the complete pip log.

[pip.log](https://github.com/giampaolo/psutil/files/1959839/pip.log)

Thanks for your help!

Regards

**Comment by msfrucht** [comment]
Setuptools version is too low for using Visual Studio 2017 instead of standalone VC++14 build tools.

Requirement already satisfied: setuptools in c:\program files (x86)\python36-32\lib\site-packages (from python-daemon<2.2,>=2.1.1->apache-airflow) (28.8.0)

https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.0_with_Visual_Studio_2017_.28x86.2C_x64.2C_ARM.2C_ARM64.29

You need at least version 34.4.0. Can you try updating and try again?

**Comment by giampaolo** [comment]
Closing this out.

**Comment by andocromn** [comment]
I know this has already been closed, I'm sure this is somehow Microsoft's fault, and i certainly don't have a solution to offer...

Just the comment its unreasonable to install over 5GB of visual studio to install this python package.  it was less work to copy the python program files from my desktop to my laptop than to install 5GB onto my laptop.  just saying
