### ISSUE TITLE
psutil-5.4.7 Failes to install on AIX 6.1 

### ISSUE THREAD

**Issue by linhan818612** [giampaolo/psutil#1329]
I am trying to install psutil 5.4.7 on AIX6.1.There is no pip.
 Python2.7.6
`python setup.py install`
error info:
`"psutil/_psutil_aix.c", lin 246.24: 1506-275 (S) Unexpected text procinfo encountered.`
`"psutil/_psutil_aix.c", lin 246.5: 1506-045 (S) Undeclared identifier perfstat_process_t.`
`"psutil/_psutil_aix.c", lin 225.33: 1506-045 (S) Undeclared identifier procinfo.`
`"psutil/_psutil_aix.c", lin 519.22: 1506-022 (S) "if_iqdrops: is not a member of "struct {...}.`
`"psutil/_psutil_aix.c", lin 519.22: 1506-022 (S) "xmitdrops: is not a member of "struct {...}.`

Does anyone have the same problem?

**Comment by giampaolo** [comment]
@wiggin15 any idea?

**Comment by wiggin15** [comment]
I assume that AIX 6.1 contains an older version of "libperfstat" that doesn't have these members (`xmitdrops` and `if_iqdrops` in `perfstat_netinterface_t`). I only have AIX 7.1 and AIX 7.2 so I can't verify this, and the versioning / changes in libperfstat aren't documented properly anywhere (we had another problem with undocumented changes to this library in #1154).
This time the struct exists, but its version is different. We'll need to disable `net_io_counters` based on, probably, `CURR_VERSION_NETINTERFACE`.
@linhan818612 can you please run on your environment the following command?

`grep CURR_VERSION_NETINTERFACE /usr/include/libperfstat.h`

On my systems, this value is "3" so we can probably just check for this version.

**Comment by giampaolo** [comment]
> Corporate users of AIX move very (very) slowly so it is still in use, but we need to decide whether we support it in psutil.

Mmm... I would say it's better to support AIX 6.1 if possible. 

> We'll need to disable net_io_counters based on, probably, CURR_VERSION_NETINTERFACE.

There's also `psutil_proc_io_counters`. It probably makes more sense to do a pre-processor check based on the AIX version. Something like this:

```c
// _psutil_aix.c
#ifdef AIX_VERSION_MAJ_6_1_OR_SOMETHING
static PyObject *
psutil_net_io_counters(PyObject *self, PyObject *args) {
    ...
}

static PyObject *
psutil_proc_io_counters(PyObject *self, PyObject *args) {
    ...
}
#endif 
```

...and in python:

```python
# _psaix.py
if hasattr(cext, "net_io_counters"):
     def net_io_counters():
           ...

class Process:
    if hasattr(cext, "proc_io_counters"):
        def io_counters(self):
            ...
```
PRs are welcome. =)

**Comment by wiggin15** [comment]
The problem with checking the AIX version is that availability may also depend on the TL/SP (update levels) installed, because we didn't see this in #1154, which was also about AIX 6.1 but maybe with a newer TL/SP. If we'll try to compare versions we'll have to pinpoint exactly which updates work, and also find preprocessor definitions for the update levels.
Luckily we do have the preprocessor definitions in libperfstat.h  that tell us whether structs are available and in what version. I can try to create a PR that checks `CURR_VERSION_NETINTERFACE` (==3) and `CURR_VERSION_PROCESS` (the same way we did with `CURR_VERSION_THREAD` in 70ffd22267c30e54ace550710ed5fa9a7332ca36), but I will have no way to test it.

**Comment by wiggin15** [comment]
I was able to get a hold of an AIX machine with 6.1 TL8 SP0 installed (released November 2012). I could not reproduce this problem.

@linhan818612 please specify what TL and SP you are using.
