### ISSUE TITLE
Compare issue with Process.cpu_times()

### ISSUE THREAD

**Issue by nicolargo** [giampaolo/psutil#1339]
Witht PsUtil 5.4.7, the comparison of two Process.cpu_times does not work as expected: 

```
$ ipython
In [1]: import psutil 

In [67]: p1 = psutil.Process(1575)
In [68]: p2 = psutil.Process(2937)

In [71]: p1.cpu_times()
Out[71]: pcputimes(user=1327.5, system=132.68, children_user=0.0, children_system=0.0)
In [72]: p2.cpu_times()
Out[72]: pcputimes(user=1263.44, system=654.21, children_user=0.03, children_system=0.0)

In [74]: p1.cpu_times() > p2.cpu_times()
Out[74]: True
```

It should be False. 

Only the user CPU time is take into account, not the CPU system.

Source: [Glances linked issue](https://github.com/nicolargo/glances/issues/1321)

**Comment by giampaolo** [comment]
> Only the user CPU time is take into account, not the CPU system.

Mmmm... this looks too arbitrary to me. I think the sorting logic should depend on the application (i.e. Glances). psutil just returns a namedtuple. From a user perspective I think it's just easier to implement the logic in the app itself instead of figuring out what the namedtuple default sorting order is (via psutil doc).

**Comment by nicolargo** [comment]
Process time sort is now managed by Glances.

See latest commit for detail.
