### ISSUE TITLE
Getting actual memory used by process(es)

### ISSUE THREAD

**Issue by pseudotensor** [giampaolo/psutil#1358]
http://www.pybloggers.com/2016/02/psutil-4-0-0-and-how-to-get-real-process-memory-and-environ-in-python/

I'm aware of rss, pss, and uss and what they mean.  And I'm aware of psutil's psutil.virtual_memory().available that will tell one the actual instantly available memory (without going to swap) as opposed to free that shows memory not used.

However, our problem is that often summing-up pss over a set of processes far exceeds the used memory as suggested by the amount of memory available.

E.g. on a 1.5TB memory system, pss sum can give 1.5TB, but available can be 1.0TB.

I think this is because we use datatable that uses memory mapping, and that these must be included in pss even if they don't represent real physical memory or anything related to consumed portions of available memory.

How do I get the portion of total - available that my processes take?

Thanks,
Jon

**Comment by giampaolo** [comment]
Honestly I don't know. This is more a question related to how the memory is handled by the kernel. What psutil does is merely reporting metrics as exposed by the kernel. So my suggestion is to ask this question on a linux kernel related message board.

**Comment by giampaolo** [comment]
> However, our problem is that often summing-up pss over a set of processes far exceeds the used memory as suggested by the amount of memory available.

Now that I re-read that it occurred to me that maybe expecting that the sum of all USS memory is supposed to match total memory is a wrong assumption due to shared memory. Basically, 

this is because by summing the USS of all processes you count shared memory more than once. By "shared" memory I mean, for instance, 

And basically that means that summing all processes USS does not necessarily means
