### ISSUE TITLE
leaking internal exeptions

### ISSUE THREAD

**Issue by arekm** [giampaolo/psutil#1402]
The problem is that with psutil (5.4.2) I'm getting some, internal, I guess, exceptions which shouldn't be visible externally, right? For example I'm getting psutil._exceptions.NoSuchProcess while documented is psutil.NoSuchProcess

````
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1390, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1965, in uids
    data = self._read_status_file()
  File "/usr/lib64/python3.6/site-packages/psutil/_common.py", line 337, in wrapper
    return fun(self)
  File "/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1445, in _read_status_file
    with open_binary("%s/%s/status" % (self._procfs_path, self.pid)) as f:
  File "/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 187, in open_binary
    return open(fname, "rb", **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/27862/status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myscript.py", line 72, in <module>
    process_pureftpd(pureftpd_pid)
  File "myscript.py", line 55, in process_pureftpd
    r_uid, e_uid, s_uid = p.uids()
  File "/usr/lib64/python3.6/site-packages/psutil/_common.py", line 337, in wrapper
    return fun(self)
  File "/usr/lib64/python3.6/site-packages/psutil/__init__.py", line 722, in uids
    return self._proc.uids()
  File "/usr/lib64/python3.6/site-packages/psutil/_pslinux.py", line 1401, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil._exceptions.NoSuchProcess: psutil.NoSuchProcess process no longer exists (pid=27862)
````

**Comment by giampaolo** [comment]
Yes, the `__repr__` is incorrect, but catching `psutil.NoSuchProcess` works, so it's a cosmetic fix.

**Comment by giampaolo** [comment]
Change was introduced in https://github.com/giampaolo/psutil/commit/fe68b30dacec3255b023fcefac5c9095d96a692f.
It's weird because back then I remember having verified that `__repr__` was OK. I'd rather keep those classes under `psutil/_exceptions.py` but if I can't come up with a soluzione to fix `__repr__` then I'll just move them back into `psutil/__init__.py`

**Comment by giampaolo** [comment]
@wiggin15 any comment on this (it's related to https://github.com/giampaolo/psutil/pull/1174)?

**Comment by giampaolo** [comment]
I just moved back the exceptions classes back into `__init__.py`.

**Comment by embray** [comment]
The reason setting `__repr__` doesn't work around this is that it doesn't factor into the way *tracebacks* are formatted in this way (since indeed it's using the class in traceback formatting and not the exception instance).

If it's really important for it to be displayed as `psutil.Error` one way to do that, which should work on both Python 2 and 3, would be:

```
class Error(Exception):
    __module__ = 'psutil'
```

it's a bit of a hack but perfectly well-supported (especially since the class is imported into the top-level module namespace anyways).

**Comment by embray** [comment]
BTW the relevant logic for this can be seen in in `trackback.format_exception_only()`:

```
>>> import traceback
>>> class Whatever(Exception): pass
...
>>> traceback.format_exception_only(Whatever, Whatever('oops'))
['Whatever: oops\n']
>>> class Whatever(Exception):
...     __module__ = 'psutil'
...
>>> traceback.format_exception_only(Whatever, Whatever('oops'))
['psutil.Whatever: oops\n']
```
