### ISSUE TITLE
cmdline() can now throw OSError instead of AccessDenied

### ISSUE THREAD

**Issue by amerry** [giampaolo/psutil#1443]
When trying to get the cmdline() of a process without sufficient permissions on Windows, since 5.5.1, it raises OSError instead of psutil.AccessDenied.

Behaviour with 5.5.0:

```
>>> p = psutil.Process(26944)
>>> p
psutil.Process(pid=26944, name='svchost.exe', started='10:34:01')
>>> p.cmdline()
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 712, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

PermissionError: [WinError 5] Access is denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\site-packages\psutil\__init__.py", line 768, in cmdline
    return self._proc.cmdline()
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 639, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 715, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
SystemError: <class 'OSError'> returned a result with an error set
```

Behaviour with 5.5.1:
```
>>> p = psutil.Process(26944)
>>> p
psutil.Process(pid=26944, name='svchost.exe', started='10:34:01')
>>> p.cmdline()
Traceback (most recent call last):
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 635, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 705, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36-32\lib\site-packages\psutil\__init__.py", line 669, in cmdline
    return self._proc.cmdline()
  File "C:\Python36-32\lib\site-packages\psutil\_pswindows.py", line 638, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil._exceptions.AccessDenied: psutil.AccessDenied (pid=26944, name='svchost.exe')
```

This is probably a direct result of #1398

**Comment by giampaolo** [comment]
So, the difference in behavior between 5.5.0 and 5.5.1 is correct. Practically speaking it's good that you get `AccessDenied` and you can't do anything about that unless catching AccessDenied or running the process with higher privilges.

As for the original change (#1398) I refactored that part of the code which now calls the 2 distinct methods from Python (instead of C) but it currently does not make any distinction about the Windows version against which the second method (no PEB) is tried:
https://github.com/giampaolo/psutil/blob/32c1a0d92f657487b0bd61c08c1a107e5d13bc51/psutil/_pswindows.py#L738
At this proposal I want to CC @EccoTheFlintstone and ask: in Python, should we avoid calling the `use_peb=False` method if Windows < 8.1? What happens in that case?
I know you already answered me this question bu I kind of forgot. =)

**Comment by amerry** [comment]
Wait, sorry, I listed those the wrong way around. 5.5.0 has the right behaviour - throws AccessDenied - and 5.5.1 has the wrong behaviour - throws OSError.

One of my scripts broke when I upgraded, because I was throwing away AccessDenied, but that no longer works with 5.5.1.

**Comment by giampaolo** [comment]
Do you have Visual Studio installed? Could you try current GIT master version?
https://github.com/giampaolo/psutil/blob/master/INSTALL.rst#windows

**Comment by amerry** [comment]
I do! Compiling was surprisingly painless. And it looks like the problem doesn't exist on master:

```
>>> psutil.__version__
'5.6.0'
>>> p = psutil.Process(26944)
>>> p
psutil.Process(pid=26944, name='svchost.exe', started='10:34:01')
>>> p.cmdline()
Traceback (most recent call last):
  File "C:\dev\third-party\psutil\psutil\_pswindows.py", line 735, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\dev\third-party\psutil\psutil\_pswindows.py", line 661, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\dev\third-party\psutil\psutil\_pswindows.py", line 738, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=False)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\third-party\psutil\psutil\__init__.py", line 786, in cmdline
    return self._proc.cmdline()
  File "C:\dev\third-party\psutil\psutil\_pswindows.py", line 664, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=26944, name='svchost.exe')
```

**Comment by giampaolo** [comment]
Beautiful. Reopening as per my question to @EccoTheFlintstone.

**Comment by EccoTheFlintstone** [comment]
_At this proposal I want to CC @EccoTheFlintstone and ask: in Python, should we avoid calling the use_peb=False method if Windows < 8.1? What happens if we do?
I know you already answered me this question but I kind of forgot. =)_

I think the kernel will return an error code stating that the class 60 (`ProcessCommandLineInformation`) you requested in `NtQueryInformationProcess` is not supported

I did a check on the windows version  (being >= 8.1) before calling this to avoid this case  (and calling  `NtQueryInformationProcess` for nothing)

**Comment by giampaolo** [comment]
This was solved as part of https://github.com/giampaolo/psutil/pull/1446. Closing and releasing a new version very soon (kind of high priority).
