### ISSUE TITLE
Windows getloadavg moving averages are incorrect

### ISSUE THREAD

**Issue by bolterr** [giampaolo/psutil#1552]
**Platform**
* Windows
* 5.6.3

**Bug description**
Thanks for implementing getloadavg for windows in psutil/psutil/arch/windows/wmi.c 

I think that there was a slipup with the factors:

#define LOADAVG_FACTOR_1F  0.9200444146293232478931553241
#define LOADAVG_FACTOR_5F  0.6592406302004437462547604110
#define LOADAVG_FACTOR_15F 0.2865047968601901003248854266

LOADAVG_FACTOR_1F  is good but I think LOADAVG_FACTOR_5F and LOADAVG_FACTOR_15F should be as follows:

#define LOADAVG_FACTOR_5F  0.9834714538216174894737477501  // 1/exp(5/300)
#define LOADAVG_FACTOR_15F 0.9944598480048967508795473395  // 1/exp(5/900)

This better matches linux/sched/loadavg.h:

LOADAVG_FACTOR_1F  = 1884/2048= 0.92...
LOADAVG_FACTOR_5F  = 2014/2048= 0.98...
LOADAVG_FACTOR_14F  = 2037/2048= 0.99...

Sorry, I would post a pr if I could.

**Comment by giampaolo** [comment]
@ammaraskar do you agree with the analysis?

**Comment by ammaraskar** [comment]
Aah yeah, this seems to be right. The calculations and wolfram links are provided here: https://github.com/giampaolo/psutil/issues/1484#issuecomment-481893394

were wrong due to the brackets, it should have been `1/exp(5 / (60*5))` but instead I used `1/exp(5 / 60*5)` which gives a completely different result. 

Sorry about that, I'll make a PR to fix it.

**Comment by giampaolo** [comment]
Thanks man.
