### ISSUE TITLE
Questions about the performance of psutil

### ISSUE THREAD

**Issue by YoshuaNava** [giampaolo/psutil#1772]
Hi,
First of all, thank you very much for this library. It is amazing and I personally find it really useful for my work.

I would like to ask you some questions about the performance of psutil, specially:

1. Which commands are expected to take the most resources to process?
2. Is there any limit to the sampling rate of any of the methods? (e.g. X 'method can't be run faster than Y Hz because the backend never goes faster than that')
3. What is the finest sampling time that you have achieved in your tests?
4. I want to use this library to fetch metrics at 400 to 800 Hz, from a real time process. Is that feasible?
5. How does psutil compare to other libraries in this respect?

Thank you very much in advance.

Best regards,
Yoshua Nava

**Comment by giampaolo** [comment]
Hey! Glad you appreciate it.

> Which commands are expected to take the most resources to process?

There's a script which does that, [scripts/internal/print_api_speed.py](https://github.com/giampaolo/psutil/blob/master/scripts/internal/print_api_speed.py). On my Linux box:

 ```
$ python3 scripts/internal/print_api_speed.py 
SYSTEM APIS               SECONDS
----------------------------------
cpu_count                 0.000014
disk_usage                0.000021
users                     0.000041
pid_exists                0.000063
cpu_times                 0.000063
cpu_percent               0.000073
cpu_times_percent         0.000075
virtual_memory            0.000079
boot_time                 0.000082
cpu_stats                 0.000097
swap_memory               0.000100
net_io_counters           0.000104
net_if_stats              0.000153
net_if_addrs              0.000164
disk_io_counters          0.000244
disk_partitions           0.000249
cpu_count (cores)         0.000391
cpu_freq                  0.000617
pids                      0.000659
sensors_battery           0.000862
sensors_fans              0.002155
sensors_temperatures      0.006117
process_iter (all)        0.011151
net_connections           0.018855

PROCESS APIS              SECONDS
----------------------------------
create_time               0.000001
nice                      0.000005
cwd                       0.000010
cpu_affinity              0.000010
exe                       0.000011
ionice                    0.000012
num_fds                   0.000015
status                    0.000024
cpu_times                 0.000026
memory_info               0.000027
num_threads               0.000030
ppid                      0.000031
io_counters               0.000031
num_ctx_switches          0.000032
name                      0.000033
is_running                0.000036
uids                      0.000037
cpu_percent               0.000039
gids                      0.000041
memory_percent            0.000046
open_files                0.000049
cmdline                   0.000052
threads                   0.000057
connections               0.000060
cpu_num                   0.000085
environ                   0.000089
username                  0.000304
memory_full_info          0.000763
terminal                  0.000840
memory_maps               0.002356
children                  0.007040
```

I'm not sure I understand the remaining questions. psutil speed mostly depend on what platform you're on, because the metrics are collected differently and also "grouped" differently. You may want to read this blog post I wrote some years ago which explains exactly this:
https://gmpy.dev/blog/2016/psutil-550-is-twice-as-fast
As a general advice:

1) if you're collecting more than 1 info per-process you should always use [oneshot()](https://psutil.readthedocs.io/en/latest/#psutil.Process.oneshot) ctx manager.
By doing that you usually "don't care", as psutil should already collect info as fast as possible.
2) alternatively you can use [as_dict()](https://psutil.readthedocs.io/en/latest/#psutil.Process.as_dict) which uses `oneshot()` internally
3) if you don't care about having "fresh" results you can implement a caching logic in your own app (e.g. `p.info = p.as_dict(attrs=[...])` and use `p.info` from then on instead of calling `as_dict()` again)
4) there are some methods like `ppid()` or `create_time()` which are uses an internal cache (search for "cache" in the doc to figure out which ones)
5) if you collect info about all processes every X seconds use [psutil.process_iter()](https://psutil.readthedocs.io/en/latest/#psutil.process_iter), which caches `Process` instances internally.
6) in general, the fastest / safest way to collect process info repeadetly is this:

```python
>>> import psutil, time
>>> while 1:
...     for proc in psutil.process_iter(['pid', 'name', 'username']):
...         print(proc.info)
...     time.sleep(1)
...
{'name': 'systemd', 'pid': 1, 'username': 'root'}
{'name': 'kthreadd', 'pid': 2, 'username': 'root'}
{'name': 'ksoftirqd/0', 'pid': 3, 'username': 'root'}
...
```

**Comment by giampaolo** [comment]
Extra, to benchmark the speed improvement deriving from using `oneshot()` there's also this [script](https://github.com/giampaolo/psutil/blob/master/scripts/internal/bench_oneshot.py). On my Linux box:

```
$ python3 scripts/internal/bench_oneshot.py 
15 methods involved on platform 'linux' (1000 iterations, psutil 5.7.1):
    cpu_num
    cpu_percent
    cpu_times
    gids
    memory_info
    memory_percent
    name
    num_ctx_switches
    num_threads
    parent
    ppid
    status
    terminal
    uids
    username
normal:  0.351 secs
onshot:  0.166 secs
speedup: +2.11x
```

**Comment by YoshuaNava** [comment]
Hi @giampaolo,

Your answers contains the exact information I was looking for. Thank you very much.

I consider this issue solved and I'll close it.
