### ISSUE TITLE
[macOS] Use PAGE_SIZE macro instead of getpagesize() to build on macOS big sur.

### ISSUE THREAD

**Issue by doneria-anjali** [giampaolo/psutil#1791]
During psutil library installation on mac OS 11.0 (aka Big Sur), during building, the setup fails with error:
psutil/_psutil_osx.c:516:20: error: implicit declaration of function 'getpagesize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        int pagesize = getpagesize();

Enhancement is to support installation of psutil on macOS 11.0 using python-pip by using PAGE_SIZE instead of getpagesize(). PAGE_SIZE is a macro that gives you the vm_page_size global.

**Comment by giampaolo** [comment]
Please make a PR.

**Comment by joefedorowicz** [comment]
Received the same error trying to install 5.7.3 using python 3.5.10.

Was this fixed in that version?

`    psutil/_psutil_osx.c:527:20: error: implicit declaration of function 'getpagesize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        int pagesize = getpagesize();
                       ^
    psutil/_psutil_osx.c:567:20: error: implicit declaration of function 'getpagesize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        int pagesize = getpagesize();
                       ^
    2 errors generated.
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/josephfedorowicz/virtualenvs/ds2/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3y/38591xfj2tx4jcd2fy208qk80000gn/T/pip-install-1yped8y1/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/3y/38591xfj2tx4jcd2fy208qk80000gn/T/pip-install-1yped8y1/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/3y/38591xfj2tx4jcd2fy208qk80000gn/T/pip-record-vxxeg9sk/install-record.txt --single-version-externally-managed --compile --install-headers /Users/josephfedorowicz/virtualenvs/ds2/include/site/python3.5/psutil Check the logs for full command output.`
