### ISSUE TITLE
[Linux] Change /proc path

### ISSUE THREAD

**Issue by TECHNOFAB11** [giampaolo/psutil#1845]
Looking at the code this is probably impossible to do. Still wanted to ask tho.

Is it possible to change the path to /proc? The use case would be for docker containers for example, where you could mount the hosts /proc into the container to /prochost for example. This /prochost then could be passed to psutil to get its data from that. 
Just overwriting/overmounting the /proc inside the container probably causes issues and this way you could still get the containers statistics.

It probably is too much work (seems like /proc is hard coded in some places) or it wont even work like i think ;)

**Comment by giampaolo** [comment]
You can with `psutil.PROCFS_PATH = '/new_path` which was introduced precisely the serve the "docker use-case". But keep in mind that not all info are retrieved from /proc fs. Some are implemented in C. That means that psutil APIs relying on the C extension will return info about the real OS instead of docker. To figure out which are those APIs you can take a peek at [psutil/_pslinux.py](https://github.com/giampaolo/psutil/blob/master/psutil/_pslinux.py) and search for `"cext."` and `"get_procfs_path"`.
