### ISSUE TITLE
Additional Disk Information

### ISSUE THREAD

**Issue by Severian-desu-ga** [giampaolo/psutil#1857]
Good day,

First I must say psutil is genuinely great and has so much to offer. Though I did notice that the information that can be obtained for the disks seems a bit spares. Information from os.statvfs is a handy extra, and one can simply call this in their script as well. But more information from the getconf utility may be of interest. Here is an example function that perhaps could be implemented.

     def disk_configurations(path):

          command = 'getconf -a ' + path 
          conf = os.popen(command).read()
          conf = conf.split('\n')
          conftup = []
          for item in conf: 
                item = ' '.join(item.split())
                tup = tuple(item.split(' '))
                if len(tup)==2: #get only variables with values
                    conftup.append(tup)

            confdic = dict(conftup)
            return confdic
 
A dictionary is returned with only variables that have values and provides a multitude of extra information about the disk. The only downside I can see is that the variables that are returned will differ from disk to disk. However the documentation can refer to the getconf page for more info on each variable. My apologise as well, this is just a base code, so no error handling was added.

**Comment by giampaolo** [comment]
> First I must say psutil is genuinely great and has so much to offer.

Thanks. I appreciate it. 
I didn't know `getconf` command. I'm not sure what the output it produces stands for though. It looks like a blob of data with information which doesn't even seem related with the disk. What disk info are you looking for exactly?

**Comment by Severian-desu-ga** [comment]
100% agree that it must be useful. getconf has a multitude of that, here's a link to some of the major variables it provides https://www.mkssoftware.com/docs/man1/getconf.1.asp but to point to the key ones here: maximum file and directory name sizes in bytes (useful when moving a folder or file between devices with a long name), maximum number of links a file may have,  maximum number of files that may be open at any time, and boolean responses to whether the device allows: ownership changes {chown}, and  error handling with file name lengths. 

The python function above calls the terminal command once, and all these variables can be called as keys with the same variable names as per the hyperlink above from the output dictionary.  The function is fast and memory can be cleaned quite simply before returning the a dictionary or list of tuples that you want. I think it would be a great addition to psutil, and to my knowledge, this runs all Linux systems (requires libc-bin which is either default installed or will install as part of the gcc package which is a requirement for psutil). Windows and Mac should also be able to call getconf, though I have not tested yet but documentation online suggests they can.

**Comment by giampaolo** [comment]
I see. It turns out that info is also exposed in python via `os.pathconf`.

```python
import os
for name in sorted(os.pathconf_names):
    print(name, os.pathconf('/', name))
```

...prints:

```
PC_ALLOC_SIZE_MIN 4096
PC_ASYNC_IO -1
PC_CHOWN_RESTRICTED 1
PC_FILESIZEBITS 64
PC_LINK_MAX 65000
PC_MAX_CANON 255
PC_MAX_INPUT 255
PC_NAME_MAX 255
PC_NO_TRUNC 1
PC_PATH_MAX 4096
PC_PIPE_BUF 4096
PC_PRIO_IO -1
PC_REC_INCR_XFER_SIZE -1
PC_REC_MAX_XFER_SIZE -1
PC_REC_MIN_XFER_SIZE 4096
PC_REC_XFER_ALIGN 4096
PC_SOCK_MAXBUF -1
PC_SYMLINK_MAX -1
PC_SYNC_IO -1
PC_VDISABLE 0
```

It seems to me the only semi-useful info are the maximum limits (path, links, etc.). I'm not sure whether they are useful enough to justify inclusion but the fact that this is portable across all UNIX/POSIX platforms is nice. Maybe we can extend the information returned by `disk_partitions()`. Maybe we can see if we can determine the same on Windows. But let me think about it. =)

**Comment by giampaolo** [comment]
It turns out `max_file_len` and `max_path_len` can be obtained on Windows as well. As for the other data, I'm not sure how to get (or whether it's worth it):
- max dir name length
- max of files that can be opened

As for permission to execute chown and max number of links: I think they are not very interesting.
[PR-1863](https://github.com/giampaolo/psutil/pull/1863) implementx `maxfile` and `maxdir` on both Windows and UNIX.
