### ISSUE TITLE
Disk Directory & File Count

### ISSUE THREAD

**Issue by RogerPlanck** [giampaolo/psutil#1897]
Hi,

Could the function os.walk be implemented into psutil? This function is quite useful when wanting to know how many directories and files exist on a disk. The only downside is the runtime can be significantly long if the disk has many folders and files. But still it would be a really nice addition to psutil's comprehensive repertoire. An example call would be like this,
```
ds = 0
fs = 0

for (root,dirs,files) in os.walk(wdir, topdown=True): 
      ds += len(dirs)
       fs += len(files)
```
Where wdir is the home directory of the disk and topdown set to True is a faster way to sort through the disk. Much appreciated if this is added. Perhaps as a new function due to its possible slow runtime on bulky disks?

**Comment by giampaolo** [comment]
I don't think it's possible. AFAIK the only way to do that is by accessing the disk.

The usual way is `os.listdir()` + `os.stat()` for each name returned by the former to figure out whether it's a file or dir.
A faster way is using `os.scandir()` which translates in 1 call per entry instead of 2, and `os.walk` already uses `os.scandir` internally.

I imagine the only way to theoretically make that faster would be by asking the native filesystem driver directly, without accessing the disk, but that would imply such a fs stores the information somewhere (e.g. when a file is created it adds an entry in a table / database of some sort), but I'm not aware of any fs which does that.
