### ISSUE TITLE
[Linux] On Librem5 psutil crash

### ISSUE THREAD

**Issue by nokernel** [giampaolo/psutil#1919]
## Summary

* OS: Linux Librem5 PureOS amber-phone
* Architecture: arm64
* Psutil version: 5.8.0
* Python version: 3.8.6
* Type:crash

## Description

Issues when using bpytop on Librem5 phone [1st I reported the issue there](https://github.com/aristocratos/bpytop/issues/266).

But looks like it's in psutil. I was able to hack it to work by changing psutil line 1455 with `secsleft = int(int(energy_now) / int(power_now) * 3600)`

Psutil does a `/` between int and bytes causing error and crash.

```
  File "/home/purism/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/psutil/__init__.py", line 2288, in sensors_battery
    return _psplatform.sensors_battery()
  File "/home/purism/.asdf/installs/python/3.8.6/lib/python3.8/site-packages/psutil/_pslinux.py", line 1455, in sensors_battery
    secsleft = int(energy_now / power_now * 3600)
TypeError: unsupported operand type(s) for /: 'int' and 'bytes'
```

**Comment by asmca** [comment]
it also happens on other devices that shows 'current_now' item value  NEGTIVE.
------------------------
suse@suse-lc:~$ uname -a
Linux suse-lc 4.19.71-arm64-desktop #1 SMP PREEMPT Thu Jul 15 14:18:15 CST 2021 aarch64 GNU/Linux
suse@suse-lc:~$ cat /sys/class/power_supply/Battery/current_now 
-634000

------------------------
As mentioned  in : https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-power

the negtive value may means："Valid values: Represented in microamps. Negative values are used for discharging batteries,"

------------------------

the problem is  that "isdigit()" function failed on negtive number:
EX:
>>> "5".isdigit()
True
>>> "-5".isdigit()
False

above fix avoids using "isdigit()" function, it works.
