### ISSUE TITLE
[macOS Apple Silicon] Installation fails due to compiler errors 

### ISSUE THREAD

**Issue by zachriggle** [giampaolo/psutil#1945]
## Summary

* OS: macOS
* Architecture: Apple M1
* Psutil version: Not applicable
* Python version: Python 3.8.2
* Type: wheels

## Description

When attempting to install psutil on an Apple Silicon Mac mini running Big Sur, I encounter the following compiler error when building `psutil/_psutil_posix.c`

```
    psutil/_psutil_posix.c:514:21: error: duplicate case value '16'
                    case(IFM_1000_T):
                        ^
    psutil/_psutil_posix.c:508:21: note: previous case defined here
                    case(IFM_1000_TX):
                        ^
    1 error generated.
    error: command 'xcrun' failed with exit status 1
```

**Comment by giampaolo** [comment]
Mmm I don't understand. I can't see anything wrong with the code:
https://github.com/giampaolo/psutil/blob/6bdde37049ba9fae31ccf83620468f77a6b9f396/psutil/_psutil_posix.c#L508-L514
Since I cannot reproduce it, if you're proficient with C, could you try downloading latest master version from GIT, try to build from sources and see if you can fix it?

```
git clone git@github.com:giampaolo/psutil.git
cd psutil
make build
```

**Comment by zachriggle** [comment]
It seems that the issue is specific to the build of Python installed by my company.  Using `python3.9` from Homebrew works.

**Comment by giampaolo** [comment]
Re-opening. Whoever can reproduce it, please provide a patch.
