### ISSUE TITLE
[Win] Windows wheels not available on pypi for 5.9.2

### ISSUE THREAD

**Issue by silvanbrummen** [giampaolo/psutil#2134]
## Summary

* OS: Windows
* Architecture: 64bit, 32bit
* Psutil version: 5.9.2
* Python version: python3
* Type: wheels

## Description

psutil 5.9.2 wheels for Windows architectures are not (yet) available on pypi.org 

They used to be available for version 5.9.1:
https://pypi.org/project/psutil/5.9.2/#files
https://pypi.org/project/psutil/5.9.1/#files

Thanks in advance,

Sil

**Comment by BenjaminHamon** [comment]
Thanks for posting, I tried to alert about it on the release post (https://groups.google.com/g/psutil/c/W4AHaf5S1kY) but apparently replies need to be approved.

Note that this means the pip install falls back to non-wheel distribution, and since psutil requires Build Tools for C++, it is likely to fail.

**Comment by giampaolo** [comment]
I don't know why but some windows wheels were not uploaded indeed. I just uploaded them right now.

**Comment by silvanbrummen** [comment]
Thanks for the quick action
