### ISSUE TITLE
No attribute getpagesize

### ISSUE THREAD

**Issue by willysr** [giampaolo/psutil#2181]
## Summary

* OS: Slackware-Current Linux
* Architecture: 64bit
* Psutil version: 5.9.4
* Python version: 3.9.15
* Type: core

## Description
I have been trying to upgrade locust and psutil is one of the requirements
I have installed all dependencies and build latest locust, but when i tried to run locust, it failed with the following error message
```
  File "/usr/lib64/python3.9/site-packages/psutil/_pslinux.py", line 87, in <module>
    PAGESIZE = cext_posix.getpagesize()
AttributeError: module 'psutil._psutil_posix' has no attribute 'getpagesize'
```
i checked that psutil installation is just fine and i used SlackBuild to create them https://slackbuilds.org/repository/15.0/python/python3-psutil/.
is there anything missing on my installation?

**Comment by youssefadr** [comment]
I just had the same issue today when trying to install ipykernel on my conda environment. What worked for me was to downgrade psutil to 5.9.1.

**Comment by giampaolo** [comment]
Due to how `getpagesize()` is implemented ([source](https://github.com/giampaolo/psutil/blob/5b3016ba3d7429c827c992699f50c2b7ff29b023/psutil/_psutil_posix.c#L71-L83)) I don't explain how such an error condition can occur. I don't know what https://slackbuilds.org/repository/15.0/python/python3-psutil/ is. Do you have the same problem by installing psutil from PYPI? Try:

```
python3 -m pip uninstall psutil
python3 -m pip install --upgrade --force-reinstall --trusted-host files.pythonhosted.org psutil
```

**Comment by willysr** [comment]
@giampaolo yes it works fine if i used the psutil from pip

SlackBuild is the script that build the source into native Slackware packages. You can see how it build by looking at the https://slackbuilds.org/slackbuilds/15.0/python/python3-psutil/python3-psutil.SlackBuild

**Comment by willysr** [comment]
Also, SlackBuild also uses the same source from pypi https://pypi.io/packages/source/p/psutil/psutil-5.9.4.tar.gz

**Comment by willysr** [comment]
i just removed psutil from pip and install python3-psutil from SBo again and now locust works fine.
it's so strange.....

**Comment by giampaolo** [comment]
Likely, this is due to an old or a parallel installation. Perhaps you had an old version of `_psutil_posix.so` (the compiled C binary) which did not have `getpagesize()` because it referred to an old, uncleaned psutil installation.
There is a check happening at import time which I added to mitigate problems like these (by crashing sooner rather than later):
https://github.com/giampaolo/psutil/blob/5b3016ba3d7429c827c992699f50c2b7ff29b023/psutil/__init__.py#L222-L241
...but perhaps it's not perfect and/or it doesn't work when one installation is from sources and another one is from wheels or whatever.

**Comment by willysr** [comment]
ok, nice to know that
thanks for the help
