### ISSUE TITLE
[Linux / FreeBSD] evaluate using `pidfd_send_signal()` for signaling processes

### ISSUE THREAD

**Issue by giampaolo** [giampaolo/psutil#2400]
See:
https://copyconstruct.medium.com/seamless-file-descriptor-transfer-between-processes-with-pidfd-and-pidfd-getfd-816afcd19ed4

Long story short: `pidfd_getfd()` used in conjunction with `pidfd_send_signal()` would prevent signaling the wrong process PID in case PID is reused by another process. In theory this should not be a problem because psutil already pre-emptively checks if PID has been reused prior to `kill()`, `terminate()`, `send_signal()` and all "set" methods (`nice()`, `ionice()`, etc.). Still, the pseudo code below (which represents what psutil does internally) is theoretically subject to a race condition in case PID gets reused between the execution of lines 1 and 2:

```python
if not pid_reused(pid):
     send_signal(sig, pid)
```

`pidfd_getfd()` + `pidfd_send_signal()` would eliminate this theoretical risk at least for `kill()`, `terminate()` and `send_signal()` methods.

It's interesting to note how FreeBSD offers similar syscalls, called `pdgetpid()` and `pdkill()`:
https://man.freebsd.org/cgi/man.cgi?query=procdesc&sektion=4
macOS doesn't seem to have them though. 

Again, this is just a theoretical problem since we already check for PID reuse internally, so it's kind of low priority. Still, I wanted to write this down somewhere for future self-reference.

**Comment by Explorer09** [comment]
Hi. I'm not sure if you are going to propose a solution for the kernel side. Since you mentioned about tracking the process creation time in htop-dev/htop#1441, I think a long term solution to the problem is to introduce a new `kill()` system call that adds a process creation time as an argument as well as PID. Without that it won't help.
(I think the kernel developers would likely reject the idea stating it is practically not a problem.)

The `pidfd` is probably _not_ designed for the use case like ours, where we track the updates of _all_ processes rather than a specific few. `pidfd` would force the OS to reserve process references to us while a process manager is not supposed to hold such resources for a long time. It's easy to mess up when managing the `pidfd` resources.

**Comment by giampaolo** [comment]
Yes, the fact that `pidfd_getfd()` can fail with "Too many open files" after 1024 calls basically kills this proposal. I believe `pidfd_getfd()` is intended to be used by those apps which **spawn** and handle their own process children. It's not intended for htop-like which monitor all PIDs. Still, to me it looks like `pidfd_getfd()` is also racy:

```python
pid = os.fork()
fd = pidfd_getfd(pid)
pidfd_send_signal(fd)
```

If PID is reused between line 1 and 2 you have a race.

As for `kill()` accepting a creation time arg: I'm not a kernel developer, and even if an OS were to support such a function, it wouldn't be cross platform.

I've researched this topic for a while now, and the impression I got is that this problem is currently unsolvable. As long as PIDs are represented as non-unique numbers, there's nothing user space apps can do.

I think the `pid + create_time` pair strategy used by psutil is the best we can do. It's racy the same way `pidfd_getfd()` is racy, but at least it can be implemented on all platforms. The chances of incurring into the race condition depend on the OS recycling algorithm. I would expect that the OS won't immediately reuse a PID, but who knows...

**Comment by giampaolo** [comment]
Oh you're right! So `pidfd_getfd()` is not racy in that case (but it is racy if PID is not a parent's child).

**Comment by Explorer09** [comment]
FreeBSD does not allow opening arbitrary processes for file descriptors. The "process descriptors" in FreeBSD can only be created by [`pdfork(2)`](https://man.freebsd.org/cgi/man.cgi?query=pdgetpid&sektion=2&apropos=0&manpath=FreeBSD+14.0-RELEASE+and+Ports) so process managers have no way to use them (they are surely designed for parent process only).

Linux has [`pidfd_open(2)`](https://man7.org/linux/man-pages/man2/pidfd_open.2.html), which is what we can use.

**Comment by giampaolo** [comment]
Closing as per my previous https://github.com/giampaolo/psutil/issues/2400#issuecomment-2047851524.

**Comment by skissane-medallia** [comment]
@giampaolo I think there is a way to make `pidfd_send_signal` work for you, given newer Linux kernel versions. You'd use this approach:
1. `pidfd_open` to open PID
2. call `statx` on the pidfd, it will return process creation time in `stx_btime`
3. compare `stx_btime` to the start time you have recorded for the process – if they are same, it is the same process, and `pidfd_send_signal` is killing it, not some other process

This applies to Linux 6.9 and higher–although possibility some distros might backport the feature to older kernel versions.  Prior to that, `stx_btime` on the pidfd wasn't meaningful. You could test for this feature at runtime by doing pidfd_open on your own PID, and comparing the stx_btime on the pidfd with the stx_btime of "/proc/$PID"

Actually, the same change makes the inode of the pidfd a permanent non-reusable process ID. So given a pid, you can `pidfd_open` it, get its inode, then close the fd again... later if you reopen the same pid, and compare the inode, if they are same it is the same process, if they are different it is recycling. In theory, this is safer than using the process creation time, since if time runs backwards (someone resets the system wall clock), the combination (creation time, PID) can be reused, but the pidfd inode will be unique until the system reboots

**Comment by giampaolo** [comment]
Interesting. Worth investigating.

**Comment by Explorer09** [comment]
> 
> Actually, the same change makes the inode of the pidfd a permanent non-reusable process ID. So given a pid, you can `pidfd_open` it, get its inode, then close the fd again... later if you reopen the same pid, and compare the inode, if they are same it is the same process, if they are different it is recycling. In theory, this is safer than using the process creation time, since if time runs backwards (someone resets the system wall clock), the combination (creation time, PID) can be reused, but the pidfd inode will be unique until the system reboots

What if the inode recycles? Technically it _can_ get recycled. Yes i know the chance of inode collision is very slim (especially when the size of the inode is as large as 64 bits). But it technically doesn't have a unique guarantee.

**Comment by skissane-medallia** [comment]
@Explorer09 In general, Linux does not guarantee inodes to be unique – but pidfd inodes are different, they are guaranteed to be unique – but only under Linux 6.9 and newer; prior to Linux 6.9, they weren't unique. If your code tests the kernel version is >= 6.9, then you know they'll be unique; although there is a small chance it might have been backported by a distribution to pre-6.9 Linux, but maybe one shouldn't bother even trying to support such a rare scenario. See https://github.com/torvalds/linux/blob/v6.9/fs/pidfs.c – also, here you can see that a pidfs inode is just a 64-bit counter which gets incremented for every new process, so it never gets reused: https://github.com/torvalds/linux/blob/v6.9/kernel/pid.c#L280

One complexity: on 32-bit kernels (does anyone care about them any more?), an inode is only 32-bit, so this is not reliable. However, starting in Linux 7.0 – see https://github.com/torvalds/linux/blob/v7.0/fs/pidfs.c#L70 – 32-bit kernels now put the lower 32-bits of the process inode counter in the inode, and the upper 32-bits in the generation number; whereas 64-bit kernels put the whole counter in the inode number, and the generation number is unused. So using pidfd inodes to uniquely identify processes cannot be done reliably on 32-bit kernels prior to Linux 7.0
