### ISSUE TITLE
Problems with network statistics on Solaris 10

### ISSUE THREAD

**Issue by lymanepp** [giampaolo/psutil#517]
We’ve been evaluating psutil for suitability in a cross-platform machine statistic gathering application that we maintain for internal use. We’ve had several issues on Solaris and the attached patch file contains changes that made to get it working on Solaris 10.
 
* We didn’t have any kstat network results where ks_module == “link”, so we hacked it to look for ks_name == “mac”. There is probably a better solution. The “kstat -c net”  output from several of our servers is linked below for reference. Our servers have multi-port NIC cards, so we needed to mangle ks_name + ks_instance as the key of the returned dictionary.
* The code was compiled as 32-bit code to match our Python installation. The #if code assumes that the kstat statistics will match the number of bits used to compile. That is not a valid assumption. A hack was made to check at runtime.

This patch is not ready to merge, but I would be happy to get feedback to make it acceptable.
 
Patch - https://gist.github.com/lymanepp/c5e403df4cbd73561d9a
Kstat output (server 1) - https://gist.github.com/lymanepp/2d105d01da798760f2c5
Kstat output (server 2) - https://gist.github.com/lymanepp/2b6c103ff97fdf5995f2

**Comment by wiggin15** [comment]
I think that instead of checking `strcmp(ksp->ks_name, "mac")` you could check `strcmp(ksp->ks_module, "e1000g")`. Then you'll get the `e1000g#` interfaces and the `ks_name:ks_instance` hack won't be needed. In fact, I think net_io_counters shouldn't be returning the `mac` interfaces at all, since those interfaces don't show in `ifconfig -a`.
In other words: in Solaris 10, ks_module is 'e1000g' and not 'link', that's all.

**Comment by giampaolo** [comment]
This was fixed in https://github.com/giampaolo/psutil/pull/680

**Comment by lymanepp** [comment]
Thank you!!
