### ISSUE TITLE
Enhancement: get threads per core

### ISSUE THREAD

**Issue by linlinlinlin** [giampaolo/psutil#550]
Is it possible add a feature: get thread(s) count per core

**Comment by linlinlinlin** [comment]
Thanks for your reply.
In my device, it have one logical CPU and have two cores.Each cores have **2** threads.
So, the result is
```
>>> psutil.cpu_count(logical=False)
1
>>> psutil.cpu_count(logical=True)
4
```
So, now I am parsing `/proc/cpuinfo` by myself.

**Comment by giampaolo** [comment]
Ah I see what you mean. Then no, right now you can't determine that kind of info with psutil. But why do you need to know that?

**Comment by mrvn** [comment]
It would be nice to get the counts for sockets (cpus), cores and threads. But I don't think a simple count() will do. Potentially you can have multiple cpus with different core and thread counts. And some cores or threads can be powered down.

So maybe it would make sense (under linux) to parse /proc/cpuinfo and/or /sys/bus/cpu/devices/cpu*/topology/* and generate a tree-ish structure. Top level would be the sockets (physical_package_id), next level the cores and the threads as leaves. The top level would have cpu, core and thread counts. The lower levels would have more specific counts. E.g. cpu_tree()[0][2].thread_count() would be the number of threads on core 2 in physical package 0.

At that point it would be nice to include the cpu frequency as well. But maybe that's better left to another issue.

**Comment by giampaolo** [comment]
I think there's already a lot of confusion around the concept of CPU cores, sockets, non/logical cores etc. and how they differ. 
I think it's safe to assume that what users need most of the times is to figure out the number of all `logical` cores in order to spawn exactly that many subprocesses. 
psutil provides that as `psutil.cpu_count(logical=True)`, which is the same provided by stdlib `multiprocessing.cpu_count()` and `os.cpu_count()`.
psutil pushes that a little further and also provides `psutil.cpu_count(logical=False)` which returns the number of physical cores only (hyper thread CPUs are excluded).
I'm not sure how many users need that but I think they are not many as it's a very specific use case already.

With that said, to me returning per CPU sockets, threads or even frequency is even more specific and potentially useless as I expect very few people would be using that and the people NOT using those things will be even more confused. 
Last but not least this may be easy to retrieve on Linux but I have no idea about the other platforms.

My main concern remains the use case though: except for some very specific circumstances my feeling is that nobody would be needing this.

**Comment by mrvn** [comment]
Well, the topology with sockets, cores and threads is only of interest for high performance computing code where you optimize to get those last percentage points out of the hardware.

On the other hand the frequency would be very useful (even required) to monitor the system utilization. What's the point of plotting the %cpu used if you don't know where the cpu was running at 800MHz or 1600MHz?

**Comment by giampaolo** [comment]
Mmmm I see where you're getting at. A function returning information about CPU stats such as frequency etc. might be interesting to have. Some thoughts:

- I'm not sure whether a tree is what we really want. I think about `lscpu` command on Linux which returns:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 58
Stepping:              9
CPU MHz:               800.000
BogoMIPS:              4789.19
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              4096K
NUMA node0 CPU(s):     0-3
```
- after seeing lscpu output I wonder whether we should return a single namedtuple containing  all the info instead of iterating over all CPUs. Why would you want a per-cpu structure instead of a single namedtuple referencing all CPUs?
- alternatively `cpu_stats` function (or whatever its name will be) can return a namedtuple by default and a list of namedtuples if passed `percpu=True` - we already have different functions like this (`cpu_*(percpu=False)` functions, `disk_io_counters(perdisk=False)` and `net_io_counters(pernic=False)`. 
  - This only makes sense if `frequency`, `architecture` and `byte_order` is gonna be the same for all CPU cores though - I wonder whether it can exist an hardware with two architectures (32 and 64 bit) or different frequencies. What do you think? (I'm no hardware expert).
- this should be available at least on Linux and Windows, and possibly also on OSX, which are the 3 major platforms. We should be doing some research on how to retrieve those info on there as well and figure out what information is portable across platforms.
- at a first glance it looks like the list of info which could be available on all platforms are: 
  - `frequency` (int, should be expressed in Mhz), 
  - `architecture` (int, either `32` or `64`)
  - `threads_per_core` (int)
  - `cores_per_socket` (int) 
  - `sockets` (int)
  - `byte_order` (a str either `"little"` or `"big"`, mimicking `sys.byteorder`)

**Comment by mrvn** [comment]
I only have access to systems that are homogen across all cpus (I think). But I don't think anything prevents one from mixing it up and have different cpus in a system.

Where I know it exists for sure is ARM. ARM has the conecpt of big/little systems, where that doesn't refer to byte order but cpu capabilities. You have for example 2 high power cores (big) with many functional units, out-of-order and superscalar processing and such. Next to that you have 4 low power cores (little) with few functional units and way less speed. So when the system is in standby or reading emails it runs on the little cores saving battery power and for gaming it powers up the big cores. Note: the cores have the same opcodes so code runs on either, just faster on big cores at a big power drain.

A percpu=True makes sense as I don't see the mobile market shrinking and there such mixed systems make a lot of sense and will become common.

-----

"architecture (int, either 32 or 64)" is a bad choice. The architecture is x86, x86_64, armv[5-8], mips, mips64, ... 32/64 would be bits.

-----

I didn't know lscpu existed. But I can run it on a number of different systems (all linux) on monday to get output for different numa, socket, core and thread numbers and cache sizes. I will double check if any of them have different cpus as well but I doubt it.

**Comment by giampaolo** [comment]
Progress about CPU frequency is tracked in #941. I'm gonna close this out.

**Comment by giampaolo** [comment]
For completeness, since I discovered this by accident, on OSX this information can be retrieved with `sysctl -a | grep machdep.cpu.thread_count`

**Comment by giampaolo** [comment]
Useful link for Windows: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683194(v=vs.85).aspx
