### ISSUE TITLE
psutil.disk_io_counters returns incorrect read_time and write_time on OSX

### ISSUE THREAD

**Issue by matthanley** [giampaolo/psutil#700]
From the docs,

> read_time: time spent reading from disk (in milliseconds)
> write_time: time spent writing to disk (in milliseconds)

I have a test case gathering stats every second and returning the difference but I'm getting results under full write-load conditions (running `dd` to local disk) which don't match expected behaviour; the difference between subsequent calls is greater than 1000 and generally up around 2-3000 suggesting I'm somehow writing to disk for ~2 seconds in a 1 second window. In a 5 second window, I see values of 6-7000.

I found this comment from the original implementation which suggests that these values are returned in nanoseconds:
https://code.google.com/p/psutil/issues/detail?id=206#c5

...but 3000 nanoseconds per second is far too low.

Are you able to confirm expected behaviour?

**Comment by giampaolo** [comment]
What platform are we talking about?

**Comment by matthanley** [comment]
OSX El Cap

**Comment by giampaolo** [comment]
Uhmm... that part of the code is old and I am not even the author of it so it's kinda hard for me to tell, also because it's hard to find an OSX doc references which states what metrics are used.
FWICT the relevant part is here:
https://github.com/giampaolo/psutil/blob/311287c30fceeeb7d4d381869763b191f7060ef1/psutil/_psutil_osx.c#L1551
One thing I can suggest is to change the code from this:

```
                read_time / 1000 / 1000,
```

...to this:

```
                read_time / 1000,
```

...then run `dd` again and see if the resulting value makes more sense.

**Comment by giampaolo** [comment]
Actually I've just found a reference which confirms kernel expresses those values as nanoseconds therefore the operation we do against the original value (`x / 1000 / 1000`) looks correct:
http://denemo.org/~jjbenham/gub/downloads/darwin-sdk/darwin8-sdk-0.4/System/Library/Frameworks/IOKit.framework/Versions/A/Headers/storage/IOBlockStorageDriver.h

**Comment by matthanley** [comment]
Thanks for looking into it. I'll continue to investigate.

**Comment by talestsp** [comment]
Hi, @matthanley , I am facing the same problem, have you found out what that value means?
