### ISSUE TITLE
disk_usage reports wrong info with fstype = afpfs

### ISSUE THREAD

**Issue by mannibis** [giampaolo/psutil#735]
Running OSX Mavericks and Python 2.7.11

"df - h" reports:

Filesystem Size Used Avail Capacity iused ifree %iused Mounted on
//admin@qnappro/Public 22Ti 13Ti 8.3Ti 62% 3566069303 2228848228 62% /mnt/QNAP/Public

"psutil.disk_usage('/mnt/QNAP/Public')" reports:

sdiskusage(total=6143796170752, used=-2980872609792, free=9124668780544, percent=-48.5)

The fstype is afpfs. Any ideas? The only correct stat is the Free space

disk_partitions reports:
sdiskpart(device='//admin@qnappro/Public', mountpoint='/mnt/QNAP/Public', fstype='afpfs', opts='rw,nosuid,dovolfs,dontbrowse,automounted,multilabel')

**Comment by giampaolo** [comment]
Glances says this is a psutil issue, I say this is a Python issue, Python would probably say this is an OSX or POSIX issue, because `disk_usage` function relies entirely on `os.statvfs`. =)

https://github.com/giampaolo/psutil/blob/36316de315a55dece354cf98533e647d7f62c49b/psutil/_psposix.py#L119
https://docs.python.org/2/library/os.html#os.statvfs

You will probably discover that also `shutil.disk_usage` has the same issue because it was contributed back from psutil project. In summary, it looks like `statvfs` implementation for afpfs filesystems on OSX is broken.
