### ISSUE TITLE
disk_usage() percent doesn't take reserved blocks into account (-5%)

### ISSUE THREAD

**Issue by ccztux** [giampaolo/psutil#829]
Hi!

As described here: https://github.com/NagiosEnterprises/ncpa/issues/102 the disk usage differs between df command and psutil output.

```
df -a
Filesystem           1K-blocks     Used Available Use% Mounted on
/dev/mapper/vg_mgmt1-lv_root
                      51475068 20684108  28169520  43% /
```

```
python
Python 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> psutil.disk_usage('/')
sdiskusage(total=52710469632, used=21180530688, free=28845584384, percent=40.200000000000003)
```

Is there an explanation about this?

**Comment by giampaolo** [comment]
psutil metrics are expressed in bytes, while df should show kb. As for the
percentage there's a comment in the source code explaining why it's
different but right now I am on the metro and can't check it.

**Comment by eschava** [comment]
# NB: the percentage is -5% than what shown by df due to
    # reserved blocks that we are currently not considering:
    # http://goo.gl/sWGbH

**Comment by jhomann** [comment]
More interested in the % since that doesn't give the proper percentage either since it doesn't account for the reserved blocks. Do you know of any way to account for this?

**Comment by giampaolo** [comment]
So here's my findings. Linux (not sure about other UNIXes) by default reserves 5% of total disk space for the root user so that if, say, the user home directory fills the disk, the root user and the system in general will still have 5% of space to write into /var/log and not crash in general:
http://unix.stackexchange.com/a/7964/168884

 `tune2fs` utility can be used to find the exact value of the reserved block, which is what psutil would need in order to calculate the correct percent value:
```
~/svn/psutil {master}$ sudo tune2fs  -l /dev/sda6 | grep "Reserved block" 
Reserved block count:     4607763
```

Parsing tune2fs output is a no-no thought: I just don't want to rely on it. I tried to take a look at tune2fs source code which is available here: http://git.kernel.org/cgit/fs/ext2/e2fsprogs.git. It determines this information via a `ext2fs_r_blocks_count()` function defined in `./lib/ext2fs/blknum.c` but it's not clear to me how the struct it uses is filled. Relying on tune2fs lib is also a no-no as it would require installing the C headers separately (`sudo apt-get install e2fslibs-dev` on ubuntu).

As for `df` utility. `df` is also able to print the right percentage information so it must take the reserved blocks value from somewhere. I tried to strace it (`strace df`) but I didn't notice anything interesting. The strace output is pretty short, suggesting `df` doesn't do anything particularly complex but unfortunately it seems the information doesn't come from the `/proc` fs. I will try to take a look at `df` source code later.

Another open question is what to do with other UNIX platforms. Is the reserved block something which exists in Linux only? If not how can we determine its value on other UNIX platforms?

**Comment by jhomann** [comment]
Maybe I am doing my math wrong but is this not why it's not taking them into account? In your code you currently have: `used = (st.f_blocks - st.f_bfree) * st.f_frsize`

From the Python docs for 2.7.11 [here](https://docs.python.org/2.7/library/statvfs.html#module-statvfs) we see that `F_BFREE` is actually the amount of free blocks total, not the amount that can be used by non-superusers. So when you're doing `total blocks - available = used` it's giving you the amount available for root, not the amount available for the user, you'd have to use `F_BAVAIL` to get that... is this something that could be triggered with a flag?

**Comment by giampaolo** [comment]
Yes, you are right: `statvfs()` already gives all the necessary bits. Thanks for figuring this out.
But what is wrong is not how psutil calculates the `used` space: it's the percentage which is wrong.
If you compare `df -h` and psutil you'll notice `total`, `used` and `free/avail` match, while the percentage doesn't (`df` reports a higher percentage) so we're doing something wrong in in there.

**Comment by giampaolo** [comment]
`df` source code: https://searchcode.com/codesearch/view/17947198/
Aliases for this confusing metrics are create at line 551, the percentage should be calculate later on at 610.

**Comment by giampaolo** [comment]
OK, I fixed this here: https://github.com/giampaolo/psutil/commit/3dea30d583b8c1275057edb1b3b720813b4d0f60
It was kinda complicated to get all the math right so I made sure to properly comment every value for future reference. Also, the returned values match `df -B 1` perfectly (tests here: https://github.com/giampaolo/psutil/commit/d5e56eca471f90f7f47ce31e5886c5ae3d1c2d05).

**Comment by jhomann** [comment]
Awesome this looks great, thanks for acting on this so quickly! I'm glad it wasn't as complicated as originally thought!

**Comment by giampaolo** [comment]
Yeah I'm glad too. It's not complicated because you have all the necessary pieces already in place but the math to calculate useful metrics out of those pieces is kinda hard to get right (it took me all day), suggesting a wrapper on top of `os.statvfs` is good to have.

**Comment by ccztux** [comment]
Thank you for fixing this!
