### ISSUE TITLE
process files infos lost if manipulated too fast

### ISSUE THREAD

**Issue by faical-yannick-congo** [giampaolo/psutil#839]
When a process is reading or writing too fast into a file i miss it in the psutil info about the process files.
What may be the issue? I don't think the OS is refreshing the syscalls infos that fast either. My current hack is to hang for a couple of seconds to be able to see the file infos captured.

**Comment by giampaolo** [comment]
What "psutil process files info" are you referring to? `Process.open_files`, Process.num_fds`, `Process.io_counters`, ...?

**Comment by faical-yannick-congo** [comment]
I am referring to Process.open_files.
Now that you write that. I imagine that it is cleaned by psutil when closed. Correct?
If so how can i have the info of also the closed files?

**Comment by giampaolo** [comment]
If files are open/closed too fast for psutil there's nothing you can do. `open_files` tells you which files are open in a *precise moment in time*, similarly to any other function (cpu, memory, disk, etc) and that really is it. 
As for info about closed files: the method is called `open_files` because it returns files which are *opened*. Of course if a file is closed is closed. The kernel does not keep track of that (why should it?) so there's nothing you can do.

**Comment by faical-yannick-congo** [comment]
Ok. It make sense.
I supposed open_files was referring to all the files opened since the launch of the process not the currently opened ones.
But for the purpose of profiling, there is a room then for missing what the process is doing with some files in a history sense. I suppose that you leave the purpose of handling this history of accessed files to the psutil user. Yet it is not trivial to determine the proper refresh rate so it has necessary has to come from psutil when the system call is being triggered and where we are the most accurate.
As for why it should keep track of the closed ones, profiling is one reason but for my purpose, i am writing a software management tool corrcli to generate reproducible records (https://mgi.nist.gov/cloud-reproducible-records) and i am use casing psutil as a meta data wrapper of the simulation process. The goal here is to take this record and build a container or a vm image out of it. If i am missing some files you can imagine where the problem is since i will  rerun the simulation within the container again with the same input files and validate its new output files against the recorded output files.

**Comment by giampaolo** [comment]
I see. There's no way to do this reliably via psutil. You can diminish the delay between calls but you'll always miss some of them along the way (it's a classic race condition). I would say that doing this **on a per-process basis** is not possible because it's something which should be done (and possibly be exposed) by the kernel which should either keep track of files which are opened or provide some kind of hook for it, but I am not aware of any OS doing that.

What you could do instead is "watch a directory" with pyinotify though:
https://github.com/seb-m/pyinotify

**Comment by faical-yannick-congo** [comment]
Hmmm! I see. pynotify will only help if i the assumption that all inputs and outputs files are within the process wdir. Which is too far to be realistic at all. Because i cannot guess where a files is going to be read or written into i would have to track all directories at all time. An ephemeral hope of mine was to think that i could watch every directory with pynotify. Well that was cleared when i ended up on:
OSError: Cannot initialize new instance of inotify, Errno=Too many open files (EMFILE)
I like the approach though so i will probably start looking at that and see what i can contribute to yours and pynotify code if you ever think that to be usefull to anyone than me. Thank you @giampaolo.
@wd15

**Comment by giampaolo** [comment]
No problem. Good luck.
