### ISSUE TITLE
Switch OSError to psutil.AccessDenied for net_if_stats failure

### ISSUE THREAD

**Issue by jakirkham** [giampaolo/psutil#860]
In some cases, a user may not have the proper permissions to run `net_if_stats`. If that is the case, an `OSError` is currently raised. It may be more appropriate to raise `psutil.AccessDenied` or at least it is a possibility worth considering ( https://github.com/giampaolo/psutil/issues/797#issuecomment-231904993 ). See an example of what this error looks like now below.

``` python
======================================================================
ERROR: test_ifconfig (test_misc.TestScripts)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/groups/dudman/home/kirkhamj/psutil/psutil/tests/test_misc.py", line 407, in test_ifconfig
    self.assert_stdout('ifconfig.py')
  File "/groups/dudman/home/kirkhamj/psutil/psutil/tests/test_misc.py", line 347, in assert_stdout
    out = sh(sys.executable + ' ' + exe).strip()
  File "/groups/dudman/home/kirkhamj/psutil/psutil/tests/__init__.py", line 257, in sh
    raise RuntimeError(stderr)
RuntimeError: Traceback (most recent call last):
  File "/groups/dudman/home/kirkhamj/psutil/scripts/ifconfig.py", line 80, in <module>
    main()
  File "/groups/dudman/home/kirkhamj/psutil/scripts/ifconfig.py", line 59, in main
    stats = psutil.net_if_stats()
  File "/groups/dudman/home/kirkhamj/psutil/psutil/__init__.py", line 1971, in net_if_stats
    return _psplatform.net_if_stats()
  File "/groups/dudman/home/kirkhamj/psutil/psutil/_pslinux.py", line 791, in net_if_stats
    isup, duplex, speed, mtu = cext.net_if_stats(name)
OSError: [Errno 1] Operation not permitted
```

**Comment by giampaolo** [comment]
>What is the reason for this exception in the first place? 
> Does this amount to needing to run psutil with sudo?

The reason is to have a single custom exception which can be catched across all different supported platforms and Python versions. On UNIX we may get `OSError` with EACCES or EPERM. On Windows we may get `WindowsError` with EACCES, EPERM or ERROR_ACCESS_DENIED, which is not even exposed in the `errno` module. Plus, on Python 3 this changed so that instead of `OSError` you'll get a new `PermissionError`.  `psutil.AccessDenied` is there to abstract all that complexity/differences away so the user can simply do:

```
try: 
     p.exe()   # or whatever
except psutil.AccessDenied:
     ...
```

...and that's it.

The exact same reason applies to `psutil.NoSuchProcess`. Depending on the platform we may get `OSError` with ESRCH, ENOENT or whatever. In python 3 you'll get `ProcessLookupError`, `psutil.NoSuchProcess` abstracts that away in the same way.

**Comment by giampaolo** [comment]
> Does this amount to needing to run psutil with sudo?

Yes, there's nothing else you can do. The error comes from the kernel, which is preventing you to perform that specific operation 'cause you're a limited user, and using sudo / su is the only possible workaround.

**Comment by giampaolo** [comment]
Looking back at this, I think it is better to let OSError propagate. So far AccessDenied is only raised for methods of the Process class. Extending the same behavior to system-related APIs would be a first in psutil, and since I consider this a pretty rare corner case I don't want to introduce this "difference".
Closing this out.
